title: Yat To Yeung (Bosco) 楊逸韜
url: "http://ytyeung.com"
# baseurl: "/Yat To Yeung (Bosco) 楊逸韜/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
#name: "About"
# link: "/Yat To Yeung (Bosco) 楊逸韜/"
 - name: "CV"
   link: "https://github.com/boscoyeungyt/ytyeung/blob/c334113013ba3da263c5b00c1160d8f7288111f5/Yeung_CV_Nov_2022.pdf"
 - name: "Professional Resumé"
   link: "https://github.com/boscoyeungyt/ytyeung/blob/dcbe3d4623019bddb4dd7f3e7729126425c18eb5/Yeung_resume_Aug2022.pdf"
 - name: "Twitter"
   link: "https://twitter.com/BoscoYeungyt"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/yeung317"
 - name: "Contact"
   link: "contact"
