title: Yat To Yeung (Bosco) 楊逸韜
url: "https://boscoyeungyt.github.io/ytyeung/"
# baseurl: "/Yat To Yeung (Bosco) 楊逸韜/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
#name: "About"
# link: "/Yat To Yeung (Bosco) 楊逸韜/"
 - name: "CV"
   link: "Yeung_CV_Apr_2022.pdf"
 - name: "Professional Resumé"
   link: "https://github.com/boscoyeungyt/ytyeung/blob/8c42a7b2c9ca4f75dac387b41d4cf1a7b3fee9b6/Yeung_resume_Apr2022.pdf"
 - name: "Twitter"
   link: "https://twitter.com/BoscoYeungyt"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/yeung317"
 - name: "Contact"
   link: "contact"
