title: Yat To Yeung (Bosco) 楊逸韜
url: "http://ytyeung.com"
# baseurl: "/Yat To Yeung (Bosco) 楊逸韜/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
#name: "About"
# link: "/Yat To Yeung (Bosco) 楊逸韜/"
 - name: "CV"
   link: "https://github.com/boscoyeungyt/ytyeung/blob/b3c45106f714c985c02c02b04d116737b3505569/Yeung_CV_May_2024.pdf"
 - name: "Professional Resumé"
   link: "https://github.com/boscoyeungyt/ytyeung/blob/1b8e5901d54c7f9c410e44b14b6587615f29692b/Yeung_resume_Jul_23.pdf"
 - name: "Twitter"
   link: "https://twitter.com/BoscoYeungyt"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/yeung317"
 - name: "Contact"
   link: "contact"
